# Generated by Django 4.0.7 on 2022-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_title_remove_post_url_post_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
